import Hero from '@/components/molecules/Home';
import { APP_NAME } from '@/config/app';
import { type NextPage } from 'next';
import { NextSeo } from 'next-seo';
import Link from 'next/link';
import { useRouter } from 'next/router';

const TermsAndConditions: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <NextSeo
        title={`Terms and Conditions - ${APP_NAME}`}
        description={`${APP_NAME} is a free tool that generates random development project ideas based on your preferences. Use it to kickstart your next hackathon project or find inspiration for your next side project.`}
      />
      <Hero>
        <h1 className="max-w-2xl text-4xl font-bold tracking-tight">Terms and Conditions</h1>
      </Hero>
      <div className="container mx-auto mb-12 grid grid-cols-1 gap-8 px-24">
        <div className="flex flex-col gap-4">
          <p className="text-lg">
            These Terms and Conditions govern your use of <b>{APP_NAME}</b>. By using our website, you agree to these
            Terms and Conditions.
          </p>
          <h3>User Accounts</h3>{' '}
          <p className="text-lg">
            You must be at least 18 years old to create an account on our website. You are responsible for maintaining
            the confidentiality of your account information and for all activities that occur under your account.
          </p>
          <h3>Credits</h3>
          <p className="text-lg">
            You will receive a certain number of credits when you sign up for an account and additional credits for
            being an active user. You may use these credits to generate project ideas using our website. You may not use
            multiple credits at once or transfer credits to another user.
          </p>
          <h3>Limitation of Liability</h3>
          <p className="text-lg">
            We are not liable for any direct, indirect, incidental, special, or consequential damages arising from your
            use of our website or from any project ideas generated by our website. We are not liable for any errors or
            omissions in the project ideas generated by our website.
          </p>
          <h3>Indemnification</h3>
          <p className="text-lg">
            You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from your use of
            our website or from any project ideas generated by our website.
          </p>
          <h3>Termination</h3>
          <p className="text-lg">
            We may terminate your account or restrict your access to our website at any time and for any reason, without
            notice or liability.
          </p>
          <h3>Intellectual Property</h3>
          <p className="text-lg">
            We do not claim any ownership over the project ideas generated by our website. All project ideas generated
            by our website are the intellectual property of the user who submitted the prompt. However, by using our
            website, you grant us a non-exclusive, worldwide, royalty-free, perpetual, and irrevocable right to use,
            reproduce, modify, adapt, publish, translate, distribute, and display the project ideas generated by our
            website for promotional purposes.
          </p>
          <h3>Use of Website</h3>
          <p className="text-lg">
            Our website is provided for informational and entertainment purposes only. You may use our website and the
            project idea generator for personal or commercial purposes. You may not use our website or the project idea
            generator for any illegal or unauthorized purpose.
          </p>
          <h3>User Generated Content</h3>
          <p className="text-lg">
            By submitting a prompt to our website, you represent and warrant that you have all necessary rights to the
            prompt, including any intellectual property rights, and that the prompt does not infringe on any third party
            rights. You also grant us the right to use the prompt to generate a project idea and to display the project
            idea on our website.
          </p>
          <h3>Limitation of Liability</h3>
          <p className="text-lg">
            We make no representations or warranties of any kind, express or implied, about the completeness, accuracy,
            reliability, suitability or availability with respect to our website or the information, products, services,
            or related graphics contained on our website for any purpose. Any reliance you place on such information is
            therefore strictly at your own risk. In no event will we be liable for any loss or damage including without
            limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of
            data or profits arising out of, or in connection with, the use of our website.
          </p>
          <h3> Personal Data</h3>{' '}
          <p className="text-lg">
            We take the protection of your personal data seriously. In order to comply with the General Data Protection
            Regulation (&quote;GDPR&quote;), we have implemented a{' '}
            <Link href="/privacy" className="text-accent">
              Privacy Policy
            </Link>{' '}
            that explains how we collect, use, and share personal data.
          </p>{' '}
          <h3>Modifications to Terms and Conditions</h3>
          <p className="text-lg">
            We reserve the right to modify these terms and conditions at any time without notice. By continuing to use
            our website after any modifications, you agree to be bound by the updated terms and conditions.
          </p>
          <h3>Governing Law</h3>
          <p className="text-lg">
            These terms and conditions shall be governed by and construed in accordance with the laws of France. Any
            dispute arising out of or in connection with these terms and conditions shall be subject to the exclusive
            jurisdiction of the courts of France.
          </p>
          If you have any questions or concerns about these terms and conditions, please contact us on our Discord
          server.
          <i className="">
            Last updated: <b>May 5, 2023</b>
          </i>
        </div>
      </div>
    </>
  );
};

export default TermsAndConditions;
